import { useState, type ReactNode } from 'react';
import { syntheticTour } from '@/lib/public-demo';
import { tourNotes, tourSummary, type AgentScenario, type TourAction, type TourState } from '@/lib/tour-model';
import styles from './tour.module.css';

export type SceneProps = { state: TourState; act: (action: TourAction, message: string) => void; go: (id: string) => void };
function Card({ title, children }: { title: string; children: ReactNode }) {
  return <article className={styles.card}><h4>{title}</h4>{children}</article>;
}
function Facts({ rows }: { rows: readonly (readonly [string, string])[] }) {
  return <dl className={styles.facts}>{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;
}
function Trail({ items }: { items: readonly string[] }) {
  return <ol className={styles.trail}>{items.map((item, i) => <li key={item}><span>{String(i + 1).padStart(2, '0')}</span>{item}</li>)}</ol>;
}
export function Jump({ go, id, children }: { go: SceneProps['go']; id: string; children: ReactNode }) {
  return <button type="button" className={styles.textButton} onClick={() => go(id)}>{children} <span aria-hidden="true">↗</span></button>;
}

function Relationships({ state, go }: SceneProps) {
  const [selected, setSelected] = useState(0);
  const contacts = [
    ...syntheticTour.contacts.slice(0, state.converted ? 3 : 2),
    ...(state.imported ? [
      { name: 'Casey Example', context: 'Independent — fictional', status: 'New', next: 'Review imported context' },
      { name: 'Morgan Demo', context: 'Independent — fictional', status: 'New', next: 'Review imported context' },
    ] : []),
  ];
  const person = contacts[selected] ?? contacts[0];
  const isImported = ['Casey Example', 'Morgan Demo'].includes(person.name);
  return <div className={styles.split}><div className={styles.recordList} aria-label="Fictional contacts">{contacts.map((contact, index) => <button key={contact.name} onClick={() => setSelected(index)} aria-pressed={selected === index}><span className={styles.avatar}>{contact.name.split(' ').map((part) => part[0]).join('')}</span><span><strong>{contact.name}</strong><small>{contact.context}</small></span></button>)}{state.imported && <p>+2 sample contacts imported · Casey and Morgan</p>}</div><Card title={person.name}><p>{person.context}</p><Facts rows={[
    ['Lifecycle', person.status], ['Next step', person.next], ['Source', person.name === 'Riley Demo' ? 'Introduction from Avery' : isImported ? 'Sample CSV import' : 'Direct introduction'], ['Tags', selected === 0 ? 'Launch · returning customer' : isImported ? 'Sample import' : 'Workshop · new relationship'],
  ]}/>{!isImported && <blockquote>“Keep the next step visible, and check the project context before reaching out.” <cite>Fictional meeting note</cite></blockquote>}<Trail items={selected === 0 ? [state.taskDone ? 'Launch follow-up completed in this demo' : 'Launch follow-up due Friday', state.ticketResolved ? 'Delivery issue resolved in this demo' : 'Delivery issue needs review', state.invoice === 'paid' ? '$4,800 payment receipt recorded' : 'Q-104 · $4,800 workshop scope agreed'] : isImported ? ['Sample CSV validated', 'Contact added in this demo', 'Context review still needed'] : ['Introduction recorded', 'Context reviewed', 'Next step agreed']}/><div className={styles.actions}><Jump go={go} id="pipeline">{selected === 0 ? 'Connected opportunity' : 'Explore opportunities'}</Jump><Jump go={go} id="tasks">{selected === 0 ? 'Related tasks' : 'Explore tasks'}</Jump><Jump go={go} id="service">{selected === 0 ? 'Support context' : 'Explore support'}</Jump></div></Card></div>;
}

function Knowledge({ go }: SceneProps) {
  const [query, setQuery] = useState('launch');
  const [selected, setSelected] = useState<string>('N-104');
  const matches = tourNotes.filter((note) => `${note.title} ${note.text}`.toLowerCase().includes(query.trim().toLowerCase()));
  const note = tourNotes.find((item) => item.id === selected)!;
  return <div className={styles.split}><div><label className={styles.field}>Search the fictional notebook<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try launch, scope, or campaign" maxLength={100}/></label><div className={styles.recordList}>{matches.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} aria-pressed={selected === item.id}><span><strong>{item.title}</strong><small>{item.id} · source excerpt</small></span></button>)}{!matches.length && <p>No matching sample notes. Try “launch”, “scope”, or clear the search.</p>}</div></div><Card title={note.title}><p className={styles.label}>SOURCE {note.id} · FICTIONAL</p><blockquote>{note.text}<cite>Authored tour example · no generated answer</cite></blockquote><Facts rows={[['Connected to', note.linked], ['Saved conversation example', `What did we promise? → See ${note.id}`], ['Model status', 'No AI model connected']]}/><Jump go={go} id={note.destination}>Follow the source connection</Jump><p className={styles.note}>The development version supports notes, clips, Markdown/text imports, explicit graph links, saved conversations, portable export, and optional local semantic indexing. This tour searches only these three samples.</p></Card></div>;
}

function Today({ state, act, go }: SceneProps) {
  const [review, setReview] = useState(false);
  return <div className={styles.split}><Card title="Possible promise · Mosaic launch"><p>Avery asked for a check-in after launch. Review the delivery issue before following up.</p><blockquote>“Review the delivery issue first; promise a follow-up on Friday.”<cite>Source N-104 · Mosaic launch review</cite></blockquote><Jump go={go} id="knowledge">Inspect the evidence</Jump>{!review ? <button className={styles.primary} onClick={() => setReview(true)}>Review sample follow-up</button> : <div className={styles.inset}><Facts rows={[['Task', 'Check Mosaic launch outcome'], ['Due', 'Friday · fictional schedule'], ['Linked contact', 'Avery Sample']]}/><button className={styles.primary} disabled={state.followUp || state.paused} onClick={() => act({ type: 'followUp' }, 'Sample follow-up added to Tasks. Nothing was sent.')}>{state.followUp ? 'Added to demo tasks' : 'Confirm sample follow-up'}</button></div>}</Card><Card title="Learning & controls"><label className={styles.check}><input type="checkbox" checked={state.learning} onChange={() => act({ type: 'learning' }, state.learning ? 'Learning switched off for this tour.' : 'Learning enabled in this tour only.')}/> Learn from my explicit feedback</label><button disabled={!state.learning || state.paused || state.feedback} onClick={() => act({ type: 'feedback' }, 'Marked useful. One fictional observation retained until reset.')}>{state.feedback ? 'Marked useful · 1 observation' : 'Mark suggestion useful'}</button><div className={styles.actions}><button onClick={() => act({ type: 'pause' }, state.paused ? 'Demo assistance resumed.' : 'Demo assistance paused. New follow-ups and feedback are blocked.')}>{state.paused ? 'Resume assistance' : 'Pause assistance'}</button><button onClick={() => act({ type: 'forget' }, 'Demo learning disabled and feedback forgotten. Existing tasks remain.')}>Forget demo feedback</button></div><p>{state.paused ? 'Assistance paused.' : 'Assistance available.'} Learning is {state.learning ? 'on' : 'off'}.</p><Jump go={go} id="tasks">See demo tasks</Jump><Jump go={go} id="capabilities">Explore capability discovery</Jump></Card></div>;
}

function Agents({ state, act }: SceneProps) {
  const requestFacts: readonly (readonly [string, string])[] = [
    ['Proposal', state.scenario === 'external' ? 'Send an external message' : state.scenario === 'scope' ? 'Change a contact record' : 'Summarize relationship health'],
    ['Tool', state.scenario === 'external' ? 'External sender · unavailable' : 'Local CRM insights'],
    ['Requested scope', state.scenario === 'scope' ? 'records:write · not granted' : state.scenario === 'external' ? 'messages:send · not granted' : 'records:read'],
    ['Grant', state.scenario === 'expired' ? 'Expired yesterday' : state.scenario === 'revoked' ? 'Revoked by the owner' : '30 days remaining · read only'],
    ['Sample budget', state.scenario === 'budget' ? '10 credits left · 11 credit estimate' : '10 credits left · 1 credit estimate'],
  ];
  const reasons: Record<AgentScenario, string> = { valid: 'records:read granted · 30-day sample grant · within budget', scope: 'Denied: records:write is not granted.', budget: 'Denied: estimate exceeds remaining budget.', expired: 'Denied: the tool grant expired.', revoked: 'Denied: the tool grant was revoked.', external: 'Denied: external tool transport is not available.' };
  return <div className={styles.split}><Card title="Studio assistant · local simulator"><label className={styles.field}>Test an authority boundary<select value={state.scenario} onChange={(event) => act({ type: 'scenario', value: event.target.value as AgentScenario }, 'Sample request changed. Evaluate it again.')}>
    <option value="valid">Valid read-only insight</option><option value="scope">Ungranted write scope</option><option value="budget">Budget exceeded</option><option value="expired">Expired grant</option><option value="revoked">Revoked grant</option><option value="external">External message sending</option>
  </select></label><Facts rows={requestFacts}/><p>{reasons[state.scenario]}</p><div className={styles.actions}><button className={styles.primary} onClick={() => act({ type: 'evaluate' }, state.stopped || state.scenario !== 'valid' ? 'Policy denied the sample request.' : 'Policy requires human approval before simulation.')}>Evaluate sample policy</button><button disabled={state.stopped || state.agent !== 'pending'} onClick={() => act({ type: 'approve' }, 'Human approval recorded in tour memory.')}>Approve sample request</button><button disabled={state.stopped || state.agent !== 'approved'} onClick={() => act({ type: 'execute' }, state.receipt ? 'Existing receipt DEMO-R-001 replayed. No second action or charge.' : 'Read-only simulation complete. Receipt DEMO-R-001 created.')}>Run local simulation</button></div></Card><Card title="Decision & receipt"><p className={styles.bigStatus}>{state.stopped ? 'Emergency stop active' : state.agent === 'idle' ? 'Awaiting policy evaluation' : state.agent === 'pending' ? 'Human approval required' : state.agent === 'approved' ? 'Approved for simulation' : state.agent === 'denied' ? 'Request denied' : 'Simulation completed'}</p>{state.receipt ? <><Facts rows={[['Receipt', 'DEMO-R-001 · immutable sample'], ['Result', 'Read-only review of the fictional studio'], ['External effects', 'None'], ['Replay', 'Same receipt · no repeat spend']]}/><p>Evaluate, approve, and run again to see the same receipt returned.</p></> : <p>No execution receipt yet. Approval alone does not run the simulator.</p>}<button className={styles.danger} disabled={state.stopped} onClick={() => act({ type: 'stop' }, 'Emergency stop active. Further approvals and executions are blocked; existing receipt remains visible.')}>Emergency stop</button><p className={styles.note}>Reset the tour to clear the stop. Real agent receipts, policy checks, budgets, and traces are enforced by the installed server; this is an illustrative rehearsal.</p></Card></div>;
}

function Governance() {
  const [profile, setProfile] = useState('personal');
  return <div className={styles.split}><Card title="Workspace profile"><label className={styles.field}>Compare defaults<select value={profile} onChange={(event) => setProfile(event.target.value)}><option value="personal">Personal</option><option value="business">Business</option><option value="enterprise">Enterprise</option></select></label><Facts rows={[['Identity', 'One owner in the current release'], ['Relationships', profile === 'personal' ? 'Up to 500' : 'Up to 1,000'], ['Service default', profile === 'personal' ? 'Off' : 'On'], ['Agent limit', profile === 'personal' ? '1' : profile === 'business' ? '10' : '100'], ['Agentic capabilities', 'Available across all three profiles']]}/><p>Profiles set defaults and limits. Overrides in an installed workspace are reversible; changing a profile does not create a product fork.</p></Card><Card title="Sample security event"><Facts rows={[['Event', 'agent.run.approved'], ['Actor', 'Fictional workspace owner'], ['Workspace', 'Liberty Bicycle Studio'], ['Evidence', 'Receipt DEMO-AUDIT-008'], ['History', 'Append-only in an installed workspace']]}/><p>Server authorization derives the workspace from verified identity. A role label in a demo is not a grant of access.</p><p className={styles.note}>This profile selector is a comparison only; all tour areas stay available to every audience.</p></Card></div>;
}

function Architecture({ go }: SceneProps) {
  const actors = [{ kind: 'Human', name: 'Avery Sample', role: 'Customer relationship and explicit contact context' }, { kind: 'Organization', name: 'Mosaic Coffee', role: 'Shared commercial context for related records' }, { kind: 'Service', name: 'Import adapter', role: 'A bounded source of records; no unrestricted authority' }, { kind: 'Agent', name: 'Studio assistant', role: 'Time-bounded tool grants, approval, and a local receipt' }];
  const [selected, setSelected] = useState(0);
  return <><div className={styles.actorGrid}>{actors.map((actor, i) => <button key={actor.kind} aria-pressed={selected === i} onClick={() => setSelected(i)}><small>{actor.kind}</small><strong>{actor.name}</strong></button>)}</div><Card title={actors[selected].name}><p>{actors[selected].role}</p></Card><div className={styles.planeGrid}>{[['Control', 'Identity, workspace, roles, capabilities, audit'], ['Data', 'Records, notes, links, receipts, private files'], ['Integration', 'Import/export, cursors, delivery receipts'], ['Agent', 'Grant → policy → approval → simulation → receipt']].map(([title, text]) => <Card key={title} title={`${title} plane`}><p>{text}</p></Card>)}</div><Jump go={go} id="agents">Try the agent authority boundaries</Jump></>;
}

export default function TourScene({ id, ...props }: SceneProps & { id: string }) {
  const { state, act, go } = props;
  const totals = tourSummary(state);
  if (id === 'relationships') return <Relationships {...props}/>;
  if (id === 'knowledge') return <Knowledge {...props}/>;
  if (id === 'today') return <Today {...props}/>;
  if (id === 'agents') return <Agents {...props}/>;
  if (id === 'governance') return <Governance/>;
  if (id === 'architecture') return <Architecture {...props}/>;
  if (id === 'overview' || id === 'reports') return <><div className={styles.metrics}>{[[String(totals.contacts), 'Contacts', '2 initial + conversions/imports'], ['$42,800', 'Open pipeline', '3 fictional opportunities'], [`$${totals.cash.toLocaleString('en-US')}`, 'Payments recorded', 'Changes with the invoice demo'], [String(totals.openTasks), 'Open tasks', `${totals.openTickets} open support ticket`]].map(([value, label, note]) => <article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div>{id === 'overview' ? <div className={styles.split}><Card title="Close the loop with Mosaic Coffee."><p>Avery’s project connects a $4,800 opportunity, an agreed scope, a delivery question, and a Friday follow-up.</p><Jump go={go} id="relationships">Open synthetic context</Jump></Card><Card title="Try a complete business journey"><Trail items={['Convert Riley’s introduction', 'Move a deal and issue an invoice', 'Record payment and review the report']}/><Jump go={go} id="leads">Start with the lead</Jump></Card></div> : <><Card title="Where the pipeline stands"><div className={styles.bars}>{syntheticTour.pipeline.map((deal, i) => <div key={deal.name}><span>{deal.name}</span><div><i style={{ width: `${[20, 58, 100][i]}%` }}/></div><strong>{deal.value}</strong></div>)}</div></Card><div className={styles.actions}><Jump go={go} id="billing">Change the payment total</Jump><Jump go={go} id="tasks">Complete a task</Jump><Jump go={go} id="service">Resolve a ticket</Jump></div><p className={styles.note}>Installed reports also include weighted forecast, sources, activities, invoice aging, and support breakdowns. These bars show unweighted opportunity values.</p></>}</>;
  if (id === 'leads') return <div className={styles.split}><Card title="Riley Demo · fictional lead"><Facts rows={[['Source', 'Introduction from Avery'], ['Company', 'Independent — fictional'], ['Interest', 'Workshop planning'], ['Next step', 'Confirm introduction']]}/><button className={styles.primary} disabled={state.converted} onClick={() => act({ type: 'convert' }, 'Riley is now a sample contact. Open People & companies to inspect it.')}>{state.converted ? 'Converted to sample contact' : 'Convert sample lead'}</button></Card><Card title="Conversion result"><Trail items={['Keep the original introduction', 'Create a connected contact', 'Choose the next relationship step']}/>{state.converted && <Jump go={go} id="relationships">Find Riley in contacts</Jump>}</Card></div>;
  if (id === 'pipeline') return <><div className={styles.pipeline}>{['Exploring', 'Qualified', 'Proposal'].map((stage, stageIndex) => <div key={stage}><h4>{stage}</h4>{syntheticTour.pipeline.filter((_, i) => (i === 0 && state.proposed ? 2 : i) === stageIndex).map((deal) => <article key={deal.name}><small>FICTIONAL OPPORTUNITY</small><strong>{deal.name}</strong><p>{deal.value}</p>{deal.name.startsWith('Workshop') && <span>Mosaic Coffee · Avery Sample</span>}</article>)}</div>)}</div><div className={styles.actions}><button className={styles.primary} disabled={state.proposed} onClick={() => act({ type: 'propose' }, 'Workshop refresh moved to Proposal. Its value stays $4,800.')}>{state.proposed ? 'Workshop refresh is in Proposal' : 'Move Workshop refresh to Proposal'}</button><Jump go={go} id="billing">Open the related quote</Jump></div></>;
  if (id === 'billing') return <div className={styles.split}><Card title="Workshop refresh · $4,800"><Facts rows={[['Product', 'Planning, setup, and handover package'], ['Customer', 'Mosaic Coffee · Avery Sample'], ['Quote', 'Q-104 · accepted sample'], ['Invoice status', state.invoice === 'quote' ? 'Not created' : state.invoice], ['Amount outstanding', state.invoice === 'paid' ? '$0' : '$4,800']]}/><div className={styles.actions}><button disabled={state.invoice !== 'quote'} onClick={() => act({ type: 'invoice' }, 'Draft invoice INV-104 created from sample quote Q-104.')}>Convert quote to invoice</button><button disabled={state.invoice !== 'draft'} onClick={() => act({ type: 'issue' }, 'Sample invoice INV-104 issued.')}>Issue invoice</button><button className={styles.primary} disabled={state.invoice !== 'issued'} onClick={() => act({ type: 'pay' }, 'Sample $4,800 payment recorded. No money was charged.')}>Record sample payment</button></div></Card><Card title="Payment evidence">{state.invoice === 'paid' ? <><Facts rows={[['Receipt', 'DEMO-PAY-104'], ['Invoice', 'INV-104'], ['Recorded amount', '$4,800'], ['Balance', '$0'], ['Payment processing', 'None · simulated record only']]}/><Jump go={go} id="reports">See the reporting change</Jump></> : <><Trail items={['Convert quote', 'Issue invoice', 'Record payment', 'Keep the receipt']}/><p>A draft invoice cannot receive a payment. Try the steps in order.</p></>}</Card></div>;
  if (id === 'tasks') return <><Card title="Follow-ups in this demo"><div className={styles.task}><div><strong>Review Mosaic launch outcome</strong><p>Avery Sample · Friday · High priority</p></div><button disabled={state.taskDone} onClick={() => act({ type: 'task' }, 'Launch follow-up completed. Customer 360 and Reports now reflect it.')}>{state.taskDone ? 'Completed' : 'Complete sample task'}</button></div><div className={styles.task}><div><strong>Prepare workshop handover</strong><p>Jordan Example · Monday · Scheduled activity</p></div><span>Open</span></div>{state.followUp && <div className={styles.task}><div><strong>Check Mosaic launch outcome</strong><p>Reviewed in Today · Friday</p></div><span>Open</span></div>}{state.workflowRun && <div className={styles.task}><div><strong>Follow up on qualified lead</strong><p>Created by the sample workflow · Tuesday</p></div><span>Open</span></div>}</Card><details className={styles.details}><summary>Preview calendar export</summary><p>Example ICS event: Workshop handover · Monday · linked to Jordan Example. Installed workspaces can export calendar files; this tour creates no file or calendar event.</p></details><Jump go={go} id="relationships">See the relationship timeline</Jump></>;
  if (id === 'campaigns') return <div className={styles.split}><Card title="Autumn service campaign"><Facts rows={[['Audience', 'Returning workshop customers'], ['Planned budget', '$600 · fictional'], ['Goal', '12 workshop conversations'], ['Status', state.campaignActive ? 'Active sample plan' : 'Draft sample plan']]}/><button className={styles.primary} disabled={state.campaignActive} onClick={() => act({ type: 'campaign' }, 'Sample campaign marked active. No emails or messages sent.')}>{state.campaignActive ? 'Sample plan active' : 'Preview campaign launch'}</button></Card><Card title="What happens next"><Trail items={['Review audience and budget', 'Keep the campaign record', 'Plan and track related activities']}/><Jump go={go} id="tasks">See follow-up work</Jump><p className={styles.note}>External sending requires a future reviewed provider integration.</p></Card></div>;
  if (id === 'service') return <div className={styles.split}><Card title="T-208 · Delivery instructions unclear"><Facts rows={[['Contact', 'Avery Sample · Mosaic Coffee'], ['Priority', 'High'], ['Status', state.ticketResolved ? 'Resolved' : 'Open'], ['Related work', 'Workshop refresh']]}/><p>Fictional issue: the handover instructions missed the workshop date.</p><button className={styles.primary} disabled={state.ticketResolved} onClick={() => act({ type: 'ticket' }, 'Sample ticket resolved. The resolution appears in Customer 360 and Reports.')}>{state.ticketResolved ? 'Sample issue resolved' : 'Record sample resolution'}</button></Card><Card title="Resolution history"><Trail items={state.ticketResolved ? ['Issue captured with customer context', 'Instructions reviewed', 'Resolved: corrected workshop date confirmed'] : ['Issue captured with customer context', 'Waiting for review']}/><Jump go={go} id="relationships">Return to Avery</Jump></Card></div>;
  if (id === 'documents') return <div className={styles.split}><Card title="Workshop brief · sample document"><p className={styles.label}>DOCUMENT DEMO-DOC-104</p><blockquote>Plan a welcoming workshop, confirm the delivery date, and leave the customer with a clear handover checklist.<cite>Fictional document text embedded in this tour</cite></blockquote><Facts rows={[['Related quote', 'Q-104'], ['Contact', 'Avery Sample'], ['Classification', 'Synthetic · public tour']]}/><Jump go={go} id="billing">Open the quote</Jump></Card><Card title="Your files in your own installation"><p>Document metadata and private file bytes have a managed lifecycle. Access is checked before downloading or deleting a real document.</p><p>The sample above has no uploaded file behind it. You can explore it without granting file access.</p><Jump go={go} id="ownership">Understand backups and exports</Jump></Card></div>;
  if (id === 'capabilities') return <div className={styles.split}><Card title="Bundled pack · follow-up focus"><p>A fictional preview of a reviewed pack that makes relationship follow-ups easier to find.</p><button className={styles.primary} onClick={() => act({ type: 'pack' }, state.pack ? 'Demo pack undone.' : 'Demo follow-up pack enabled.')}>{state.pack ? 'Undo sample pack' : 'Enable sample pack'}</button>{state.pack && <div className={styles.inset}><strong>Follow-up focus</strong><p>1 sample promise ready for review.</p><Jump go={go} id="today">Review the next step</Jump></div>}</Card><Card title="Fictional public release idea"><p>Example improvement: a clearer handover checklist. A release discovery produces an implementation proposal for review.</p><button disabled={state.proposal} onClick={() => act({ type: 'proposal' }, 'Fictional proposal prepared. No software was downloaded or deployed.')}>{state.proposal ? 'Sample proposal prepared' : 'Prepare sample proposal'}</button>{state.proposal && <Facts rows={[['Problem', 'Handover dates are easy to miss'], ['Acceptance', 'Show date and source before confirming'], ['Next action', 'Human review and implementation'], ['Code installed', 'None']]}/>}</Card></div>;
  if (id === 'automation') return <div className={styles.split}><Card title="Qualified lead → follow-up task"><Trail items={['Trigger: lead qualification event', 'Condition: stage equals Qualified', 'Action: create one follow-up task']}/><div className={styles.actions}><button className={styles.primary} disabled={!state.workflowEnabled} onClick={() => act({ type: 'workflowRun' }, state.workflowRun ? 'The same sample event was already processed. No duplicate task created.' : 'Sample event processed. One follow-up task added.')}>Run sample event</button><button onClick={() => act({ type: 'workflowToggle' }, state.workflowEnabled ? 'Sample rule paused.' : 'Sample rule enabled.')}>{state.workflowEnabled ? 'Pause rule' : 'Enable rule'}</button></div></Card><Card title="Run history"><Facts rows={[['Rule', state.workflowEnabled ? 'Enabled' : 'Paused'], ['Processed sample event', state.workflowRun ? 'DEMO-EVT-001' : 'None'], ['Tasks created', state.workflowRun ? '1' : '0'], ['Repeat handling', 'Same event → same result']]}/><Jump go={go} id="tasks">Inspect task list</Jump></Card></div>;
  if (id === 'integrations') return <><div className={styles.split}><Card title="Import preview · embedded CSV"><pre className={styles.code}>{`name,email\nCasey Example,casey@example.test\nMorgan Demo,${state.importValid ? 'morgan@example.test' : 'not-an-email'}`}</pre><div className={styles.actions}><button onClick={() => act({ type: 'importPreview' }, state.importValid ? 'Preview passed: 2 valid fictional rows.' : 'Preview found row 2: invalid email. Import is blocked.')}>Preview sample CSV</button><button disabled={state.importValid} onClick={() => act({ type: 'importFix' }, 'Sample email corrected. Run preview again before importing.')}>Use corrected sample</button><button className={styles.primary} disabled={!state.importPreview || !state.importValid || state.imported} onClick={() => act({ type: 'importCommit' }, '2 sample contacts added to tour totals. No database was contacted.')}>{state.imported ? 'Sample rows imported' : 'Simulate import'}</button></div>{state.importPreview && <p>{state.importValid ? '2 valid rows · ready for this demo' : 'Row 2: invalid email · entire batch blocked'}</p>}</Card><Card title="Connections tell the truth"><Facts rows={[['CSV / JSON', 'Portable record exports'], ['ICS', 'Calendar export'], ['Reference connector', 'Cursor and retry foundation'], ['Webhook ingress', 'Device / Cloudflare only'], ['Email / calendar OAuth', 'Not shipped']]}/><p>Disconnect and credential deletion belong to an owner-controlled installation. This tour stores no credentials.</p></Card></div><Jump go={go} id="ownership">Choose a setup and recovery path</Jump></>;
  if (id === 'ownership') return <><div className={styles.planeGrid}><Card title="One device or Docker"><p>Use the local launcher with no cloud account or AI key. Your state stays on your device; the local server accepts loopback access.</p><a href="https://github.com/mlmrx/FreeCRM#run-on-one-device">Read local setup ↗</a></Card><Card title="Your own cloud"><p>Deploy with your own identity, database, and private file storage. Complete owner setup before entering records.</p><a href="/deploy">Compare Vercel & Cloudflare →</a></Card><Card title="Phone or tablet"><p>Use this tour in a mobile browser now. On your configured HTTPS installation, choose Add to Home Screen or Install app.</p><p>Private workspace data needs a live connection. Native iOS, Android, and APK packages are roadmap work.</p></Card><Card title="Export & recover"><p>CSV/JSON exports help you leave with your records. A portable snapshot excludes document bytes and is not a full recovery backup.</p><p>Back up stopped local state, or use database and private file backups for your chosen provider.</p></Card></div><div className={styles.actions}><a className={styles.primary} href="/start">Find my setup path</a><a href="/deploy/readiness">Check setup requirements →</a></div></>;
  if (id === 'community') return <div className={styles.planeGrid}>{[['Find your path', '/start', 'Choose the profile and deployment that fit your work.'], ['Learn with field guides', '/insights', 'Explore CRM practice, agents, ownership, and research.'], ['Inspect the source', 'https://github.com/mlmrx/FreeCRM', 'MIT-licensed source, setup instructions, and issues.'], ['Make a contribution', '/contribute', 'Documentation, usability, tests, and complete feature slices.']].map(([title, href, copy]) => <Card key={title} title={title}><p>{copy}</p><a href={href}>{title} →</a></Card>)}<a href="/insights/rss.xml">Follow Insights RSS →</a></div>;
  if (id === 'roadmap') return <><div className={styles.planeGrid}><Card title="Shared and enterprise work"><p>Team invitations, shared identity administration, SSO/SCIM, advanced policy authoring, and production PostgreSQL/S3 adapters.</p></Card><Card title="External action & sync"><p>Production email/calendar OAuth clients, generic outbound delivery, MCP/external agent transports, and general autonomous external execution.</p></Card><Card title="Native mobile & knowledge"><p>Native iOS/Android and APK distribution; PDF/OCR, automatic knowledge ingestion, inferred graph connections, and complete snapshot restore.</p></Card><Card title="Development previews in this tour"><p>Second brain, adaptive Today, and capability discovery are demonstrated here from unmerged development work.</p><Jump go={go} id="knowledge">Explore the knowledge preview</Jump></Card></div><a href="https://github.com/mlmrx/FreeCRM/blob/main/ROADMAP.md">Read the shared roadmap →</a></>;
  return null;
}
