/** Public, authored fiction only. Tour state is confined to this page's memory. */
export type TourStatus = 'Available' | 'Development preview' | 'Local simulator' | 'Roadmap';
export type TourSection = {
  id: string; label: string; group: string; status: TourStatus;
  title: string; summary: string; boundary: string;
  features: readonly string[]; steps: readonly string[]; related: readonly string[];
};

export const tourSections: readonly TourSection[] = [
  { id: 'overview', label: 'Workspace overview', group: 'Relationships', status: 'Available', title: 'See what needs your attention.', summary: 'One fictional studio, from a first introduction to a completed project. Follow the work without losing the relationship.', boundary: 'Every person, company, amount, and event in this tour is invented. Buttons change this demo only; reload or reset to start again.', features: ['Dashboard', 'Relationship context', 'Next steps'], steps: ['Review the open relationships and pipeline.', 'Open a person to see the work around them.', 'Follow a guided path or explore any feature.'], related: ['relationships', 'pipeline', 'tasks'] },
  { id: 'relationships', label: 'People & companies', group: 'Relationships', status: 'Available', title: 'A person, with their whole context.', summary: 'Find the conversation, company, commitment, and commercial work around a relationship.', boundary: 'Links are explicit. An empty timeline is not evidence that a relationship is inactive.', features: ['Contacts', 'Companies', 'Customer 360', 'Notes', 'Tags', 'Lifecycle', 'Record links', 'Archive'], steps: ['Choose a fictional contact.', 'Read their context and timeline.', 'Follow the connected opportunity or task.'], related: ['leads', 'pipeline', 'tasks', 'knowledge'] },
  { id: 'leads', label: 'Leads & conversion', group: 'Relationships', status: 'Available', title: 'Turn an introduction into a relationship.', summary: 'Keep the source, qualification, and next step together as a lead becomes a contact.', boundary: 'This conversion creates a fictional contact in the tour only. It does not enrich data or contact anyone.', features: ['Leads', 'Sources', 'Qualification', 'Lead conversion'], steps: ['Review Riley’s introduction.', 'Convert the synthetic lead.', 'Find Riley in People & companies.'], related: ['relationships', 'pipeline'] },
  { id: 'pipeline', label: 'Opportunities', group: 'Sales & money', status: 'Available', title: 'Move the deal. Keep the history.', summary: 'Track the stage, value, and probability of work before it becomes revenue.', boundary: 'Pipeline is a forecast. A won deal is not a payment, and a sample probability is not a prediction.', features: ['Opportunities', 'Stages', 'Probability', 'Pipeline', 'Forecast'], steps: ['Inspect the Workshop refresh opportunity.', 'Move the sample deal to Proposal.', 'Follow it into products and quotes.'], related: ['billing', 'reports'] },
  { id: 'billing', label: 'Products, quotes & invoices', group: 'Sales & money', status: 'Available', title: 'From a clear scope to a recorded payment.', summary: 'A $4,800 service package moves from quote to invoice, with each transition visible.', boundary: 'Payments are recorded, not charged. The demo does not collect card details or connect to a payment provider.', features: ['Products', 'Quotes', 'Quote-to-invoice', 'Invoices', 'Payment receipts', 'Invoice aging'], steps: ['Convert quote Q-104 to an invoice.', 'Issue the invoice before recording payment.', 'Inspect its sample receipt and reporting impact.'], related: ['reports', 'documents', 'service'] },
  { id: 'tasks', label: 'Tasks, activities & calendar', group: 'Work & service', status: 'Available', title: 'Follow through on what you promised.', summary: 'Keep a clear next step and due date beside the person and work it belongs to.', boundary: 'Activities and calendar export are available. Live Google or Microsoft calendar synchronization is not shipped.', features: ['Tasks', 'Activities', 'Priority', 'Due dates', 'Calendar', 'ICS export'], steps: ['Review the Mosaic launch follow-up.', 'Mark the sample task complete.', 'See the completed activity in Customer 360.'], related: ['relationships', 'campaigns', 'automation'] },
  { id: 'campaigns', label: 'Campaign planning', group: 'Work & service', status: 'Available', title: 'Keep a campaign connected to its work.', summary: 'Plan the autumn service campaign with a budget, audience, and follow-up tasks.', boundary: 'Campaign records do not send marketing emails. Any results shown here are fictional planning data.', features: ['Campaigns', 'Budget', 'Campaign status', 'Related activities'], steps: ['Review the fictional campaign brief.', 'Preview the planned launch.', 'Inspect the task that follows.'], related: ['tasks', 'reports', 'integrations'] },
  { id: 'service', label: 'Support tickets', group: 'Work & service', status: 'Available', title: 'Resolve the issue without losing the customer.', summary: 'The studio’s delivery issue stays connected to Avery, the project, and its resolution history.', boundary: 'Service is enabled by default in business and enterprise profiles. Resolving this sample ticket sends no notification.', features: ['Support tickets', 'Priority', 'Status', 'Resolution history'], steps: ['Inspect ticket T-208.', 'Record the sample resolution.', 'Return to the contact for the relationship context.'], related: ['relationships', 'documents', 'reports'] },
  { id: 'documents', label: 'Documents & files', group: 'Work & service', status: 'Available', title: 'Put the right document beside the work.', summary: 'Browse a fictional project brief and its link to a quote and contact.', boundary: 'The tour uses embedded sample text and accepts no uploads. Real files require configured private storage.', features: ['Documents', 'File lifecycle', 'Private storage', 'Linked documents'], steps: ['Open the sample project brief.', 'Inspect who and what it belongs to.', 'Review export and backup boundaries.'], related: ['billing', 'ownership'] },
  { id: 'reports', label: 'Reports & analytics', group: 'Intelligence', status: 'Available', title: 'Read the business behind the records.', summary: 'Compare pipeline, cash recorded, open tasks, and service work in the same fictional workspace.', boundary: 'Tour totals come from a tiny authored dataset. Revenue, weighted forecast, invoice aging, source, activity, task, and support reports in an installed workspace depend on its actual records.', features: ['Reports', 'Analytics', 'Weighted forecast', 'Revenue', 'Source analysis', 'Activity analysis', 'Task analytics', 'Invoice aging', 'Support metrics'], steps: ['Read the sample reporting snapshot.', 'Record a sample payment or close a task.', 'Return here to see the totals change.'], related: ['pipeline', 'billing', 'tasks', 'service'] },
  { id: 'knowledge', label: 'Second brain', group: 'Intelligence', status: 'Available', title: 'Find the source behind the next step.', summary: 'Search a small fictional notebook, follow its source, and see how a note connects to a relationship.', boundary: 'Second brain is available in an installed workspace. This tour uses keyword search over embedded fiction. Optional device-local Ollama is not running here; no OpenAI key or generated answer is used.', features: ['Knowledge library', 'Notes', 'Text imports', 'Knowledge graph', 'Source search', 'Citations', 'Saved conversations', 'Local AI', 'Semantic indexing'], steps: ['Search the sample notes for “launch”.', 'Open a matching source.', 'Follow its connection to Avery or the Today briefing.'], related: ['relationships', 'today'] },
  { id: 'today', label: 'Today & learning', group: 'Intelligence', status: 'Available', title: 'Know why a next step was suggested.', summary: 'A promise in a source note becomes a reviewable follow-up. Give feedback and keep control of learning.', boundary: 'Adaptive Today is available in an installed workspace. Learning and automatic adaptation start off; tour feedback is kept only while this page is open. Release discovery prepares proposals, never automatically installs code.', features: ['Daily briefing', 'Evidence', 'Reviewed follow-ups', 'Opt-in learning', 'Pause', 'Forget feedback', 'Capability packs', 'Release discovery', 'Implementation proposals'], steps: ['Read the evidence for a sample follow-up.', 'Review it before adding it to demo tasks.', 'Try feedback, pause, or forget; inspect capability discovery.'], related: ['knowledge', 'tasks', 'capabilities'] },
  { id: 'capabilities', label: 'Capability discovery', group: 'Intelligence', status: 'Available', title: 'Review an improvement before adopting it.', summary: 'See the distinction between a bundled capability pack and an idea discovered in a public release.', boundary: 'Reviewed packs and opt-in discovery are available. This tour uses a fictional release example, not a live vendor announcement; cloud scheduling still needs operator setup.', features: ['Capability library', 'Bundled packs', 'Release radar', 'Local watcher', 'Cloud scheduler', 'Reviewed proposals'], steps: ['Preview a bundled follow-up pack.', 'Undo it if it does not help.', 'Prepare a fictional implementation proposal; no code is downloaded.'], related: ['today', 'ownership', 'community'] },
  { id: 'automation', label: 'Workflow automation', group: 'Automation & agents', status: 'Available', title: 'Turn an event into a useful next step.', summary: 'A qualified lead triggers one follow-up task, with the rule and its result visible.', boundary: 'This rule is a local tour simulation. The installed platform audits workflow runs; a generic external delivery worker is not shipped.', features: ['Workflows', 'Triggers', 'Conditions', 'Task creation', 'Pause rules', 'Run history', 'Idempotency'], steps: ['Inspect the trigger, condition, and action.', 'Run the sample event once.', 'Repeat it to see duplicate protection, or pause the rule.'], related: ['leads', 'tasks', 'agents'] },
  { id: 'agents', label: 'Agent approval & stop', group: 'Automation & agents', status: 'Local simulator', title: 'See what an agent is allowed to do.', summary: 'Review a scoped request, approve it, then inspect a simulated receipt. Try the emergency stop and denial paths.', boundary: 'It cannot call a provider, mutate a CRM record, or send a message. The released agent transport is a local simulator; general external autonomous execution is not shipped.', features: ['Agent identity', 'Tool grants', 'Scope', 'Budget', 'Approval', 'Receipts', 'Traces', 'Replay protection', 'Emergency stop', 'Revocation', 'Grant expiry'], steps: ['Choose a valid, expired, ungranted, or over-budget request.', 'Evaluate policy and approve the valid sample.', 'Run once, replay the receipt, or activate emergency stop.'], related: ['architecture', 'governance'] },
  { id: 'integrations', label: 'Imports & connections', group: 'Connections & control', status: 'Available', title: 'Preview what comes in. Keep a way out.', summary: 'Compare valid and invalid sample CSV rows before a simulated import.', boundary: 'No files or credentials are accepted here. Email/calendar OAuth providers are not shipped. Webhook ingress is available on device/Cloudflare; it is disabled on native Vercel.', features: ['CSV import', 'Header mapping', 'Validation', 'CSV export', 'JSON export', 'ICS export', 'Webhooks', 'Connector cursors', 'Disconnect'], steps: ['Preview the embedded CSV sample.', 'Fix the sample invalid row before importing.', 'Inspect portability and connection status.'], related: ['relationships', 'ownership', 'architecture'] },
  { id: 'governance', label: 'Profiles & audit', group: 'Connections & control', status: 'Available', title: 'One platform, with explicit authority.', summary: 'Personal, business, and enterprise profiles change capabilities and limits within one shared platform.', boundary: 'The current product is exact-single-owner. Team invitations, shared identity administration, enterprise SSO/SCIM, and advanced policy authoring are roadmap work.', features: ['Personal profile', 'Business profile', 'Enterprise profile', 'Capability controls', 'Tenant isolation', 'Roles', 'Append-only audit', 'Reset'], steps: ['Compare the three profile defaults.', 'Inspect a sample security event.', 'Use the roadmap to distinguish foundation from future controls.'], related: ['agents', 'architecture', 'ownership', 'roadmap'] },
  { id: 'architecture', label: 'Actors & platform', group: 'Connections & control', status: 'Available', title: 'Give people, organizations, services, and agents a place.', summary: 'Inspect the four kinds of actor and the boundaries between identity, records, integrations, and agent execution.', boundary: 'Actor and API foundations exist. Agent-native transport and autonomous cross-system operation remain a research path.', features: ['Human actors', 'Organizations', 'Services', 'Agents', 'Control plane', 'Data plane', 'Integration plane', 'Agent plane', 'Relationship API'], steps: ['Select an actor in the fictional studio.', 'See its role and boundary.', 'Inspect how agent authorization precedes any action.'], related: ['agents', 'governance', 'integrations', 'roadmap'] },
  { id: 'ownership', label: 'Run, export & mobile', group: 'Get your own', status: 'Available', title: 'Choose where your real workspace lives.', summary: 'Run on one device or Docker, or configure your own cloud deployment. The responsive web app also works on a phone.', boundary: 'The tour is ready without sign-in. Your own hosted workspace needs owner login and storage. Software is MIT-licensed; infrastructure can cost money. Native APK/iOS apps are not shipped.', features: ['Local device', 'Docker', 'Vercel', 'Cloudflare', 'SQLite', 'D1', 'R2', 'Private Blob', 'PWA', 'Mobile', 'Backups', 'Data export'], steps: ['Choose a device or cloud setup path.', 'Understand export versus recovery backup.', 'Learn how the installed PWA works on a phone.'], related: ['integrations', 'governance', 'community'] },
  { id: 'community', label: 'Learn & contribute', group: 'Get your own', status: 'Available', title: 'Keep building one shared platform.', summary: 'Read the source, explore the field guides, report a reproducible issue, or choose a contribution.', boundary: 'Roadmap items describe work ahead. They are not shipped features or promised delivery dates.', features: ['MIT license', 'Source code', 'Insights', 'RSS', 'Documentation', 'Issues', 'Contributing', 'Path finder'], steps: ['Find a setup or learning path.', 'Inspect the source and open issues.', 'Use synthetic records in bug reports.'], related: ['roadmap', 'ownership'] },
  { id: 'roadmap', label: 'What is still ahead', group: 'Get your own', status: 'Roadmap', title: 'Know the boundary before you choose.', summary: 'Explore the future direction without mistaking it for functionality you can use today.', boundary: 'This page simulates the product story. Production readiness still depends on the selected release, configuration, and verification of your own installation.', features: ['Team invitations', 'SSO', 'SCIM', 'PostgreSQL', 'S3', 'Native Android', 'Native iOS', 'APK', 'Provider OAuth', 'External agent execution', 'PDF/OCR'], steps: ['Review what is available and what is pending.', 'Read the shared roadmap.', 'Choose a supported setup or contribution.'], related: ['governance', 'agents', 'ownership', 'community'] },
];

export const tourAudiences = [
  { id: 'personal', label: 'Personal & solo', profile: 'Personal profile', goal: 'Remember people. Keep your promises.', detail: 'A simple path through relationships, everyday work, and your own notes.', boundary: 'Single-owner workspace available. Knowledge and adaptive tools are opt-in and remain under your control.', path: ['overview', 'relationships', 'tasks', 'knowledge', 'today', 'ownership'] },
  { id: 'business', label: 'Business', profile: 'Business profile', goal: 'Follow the relationship from hello to payment.', detail: 'Connect sales, delivery, service, and reporting around one fictional customer.', boundary: 'Business capability foundation available for one owner. Shared team access is not shipped.', path: ['leads', 'relationships', 'pipeline', 'billing', 'tasks', 'campaigns', 'service', 'documents', 'reports', 'automation', 'integrations', 'ownership'] },
  { id: 'enterprise', label: 'Enterprise', profile: 'Enterprise profile', goal: 'Inspect control, ownership, and operational fit.', detail: 'Start with governance, then trace the records, integrations, and decisions it protects.', boundary: 'Architecture preview for enterprise evaluation. SSO/SCIM, shared administration, PostgreSQL/S3 adapters are roadmap items.', path: ['governance', 'architecture', 'relationships', 'reports', 'integrations', 'agents', 'ownership', 'roadmap'] },
  { id: 'agentic', label: 'Humans + agents', profile: 'Agentic layer · every profile', goal: 'Help a person act with clear authority.', detail: 'Move from evidence to a reviewed proposal, a bounded action, and its receipt.', boundary: 'Knowledge and adaptive assistance are available. Agent execution remains a non-external local simulator.', path: ['today', 'knowledge', 'automation', 'agents', 'capabilities', 'governance', 'ownership'] },
  { id: 'agents', label: 'Building for agents', profile: 'Actor & API research path', goal: 'Inspect the contracts behind an agent relationship.', detail: 'Explore actor types, tool permissions, failure paths, and integration boundaries.', boundary: 'Actor foundations are available. General external agent transport and autonomous operation are not released.', path: ['architecture', 'agents', 'integrations', 'governance', 'roadmap', 'community'] },
] as const;
export type AudienceId = (typeof tourAudiences)[number]['id'];
export type AgentScenario = 'valid' | 'scope' | 'budget' | 'expired' | 'revoked' | 'external';
export type TourState = {
  converted: boolean; proposed: boolean; invoice: 'quote' | 'draft' | 'issued' | 'paid';
  taskDone: boolean; ticketResolved: boolean; campaignActive: boolean;
  followUp: boolean; learning: boolean; paused: boolean; feedback: boolean;
  pack: boolean; proposal: boolean; workflowEnabled: boolean; workflowRun: boolean;
  importPreview: boolean; importValid: boolean; imported: boolean;
  scenario: AgentScenario; agent: 'idle' | 'pending' | 'denied' | 'approved' | 'executed';
  stopped: boolean; receipt: boolean;
};
export const initialTourState: TourState = {
  converted: false, proposed: false, invoice: 'quote', taskDone: false, ticketResolved: false,
  campaignActive: false, followUp: false, learning: false, paused: false, feedback: false,
  pack: false, proposal: false, workflowEnabled: true, workflowRun: false,
  importPreview: false, importValid: false, imported: false, scenario: 'valid',
  agent: 'idle', stopped: false, receipt: false,
};
export type TourAction =
  | { type: 'reset' | 'convert' | 'propose' | 'invoice' | 'issue' | 'pay' | 'task' | 'ticket' | 'campaign' | 'followUp' | 'learning' | 'pause' | 'feedback' | 'forget' | 'pack' | 'proposal' | 'workflowToggle' | 'workflowRun' | 'importPreview' | 'importFix' | 'importCommit' | 'evaluate' | 'approve' | 'execute' | 'stop' }
  | { type: 'scenario'; value: AgentScenario };
/** Tiny tour state machine; never a substitute for the server's policy enforcement. */
export function tourReducer(state: TourState, action: TourAction): TourState {
  switch (action.type) {
    case 'reset': return { ...initialTourState };
    case 'convert': return { ...state, converted: true };
    case 'propose': return { ...state, proposed: true };
    case 'invoice': return state.invoice === 'quote' ? { ...state, invoice: 'draft' } : state;
    case 'issue': return state.invoice === 'draft' ? { ...state, invoice: 'issued' } : state;
    case 'pay': return state.invoice === 'issued' ? { ...state, invoice: 'paid' } : state;
    case 'task': return { ...state, taskDone: true };
    case 'ticket': return { ...state, ticketResolved: true };
    case 'campaign': return { ...state, campaignActive: true };
    case 'followUp': return state.paused ? state : { ...state, followUp: true };
    case 'learning': return { ...state, learning: !state.learning };
    case 'pause': return { ...state, paused: !state.paused };
    case 'feedback': return state.learning && !state.paused ? { ...state, feedback: true } : state;
    case 'forget': return { ...state, feedback: false, learning: false };
    case 'pack': return { ...state, pack: !state.pack };
    case 'proposal': return { ...state, proposal: true };
    case 'workflowToggle': return { ...state, workflowEnabled: !state.workflowEnabled };
    case 'workflowRun': return state.workflowEnabled && !state.workflowRun ? { ...state, workflowRun: true } : state;
    case 'importPreview': return { ...state, importPreview: true };
    case 'importFix': return { ...state, importValid: true, importPreview: false };
    case 'importCommit': return state.importPreview && state.importValid ? { ...state, imported: true } : state;
    case 'scenario': return { ...state, scenario: action.value, agent: 'idle' };
    case 'evaluate': return { ...state, agent: state.stopped || state.scenario !== 'valid' ? 'denied' : 'pending' };
    case 'approve': return !state.stopped && state.agent === 'pending' ? { ...state, agent: 'approved' } : state;
    case 'execute': return !state.stopped && state.agent === 'approved' ? { ...state, agent: 'executed', receipt: true } : state;
    case 'stop': return { ...state, stopped: true, agent: 'denied' };
  }
}

export const tourNotes = [
  { id: 'N-104', title: 'Mosaic launch review', text: 'Avery asked for a check-in after the launch. Review the delivery issue first; promise a follow-up on Friday.', linked: 'Avery Sample · Mosaic Coffee', destination: 'relationships' },
  { id: 'N-105', title: 'Workshop scope', text: 'The Workshop refresh package includes planning, setup, and a handover session. The agreed sample price is $4,800.', linked: 'Workshop refresh · Q-104', destination: 'billing' },
  { id: 'N-106', title: 'Autumn campaign idea', text: 'Plan a service workshop for returning customers. Keep the audience and budget visible; do not send an email automatically.', linked: 'Autumn service campaign', destination: 'campaigns' },
] as const;
export function searchTourSections(query: string): readonly TourSection[] {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  return tourSections.filter((section) => terms.every((term) => `${section.label} ${section.group} ${section.status} ${section.features.join(' ')}`.toLowerCase().includes(term)));
}
export function tourSummary(state: TourState) {
  return { contacts: 2 + Number(state.converted) + (state.imported ? 2 : 0), pipeline: 42_800,
    cash: state.invoice === 'paid' ? 4_800 : 0, openTasks: 2 - Number(state.taskDone) + Number(state.followUp) + Number(state.workflowRun),
    openTickets: state.ticketResolved ? 0 : 1 };
}
